(in-package :oc)

(defmethod initialize-instance :after ((obj brep-prim-api-make-sphere) &rest initargs
				       &key center radius axis R angle1 angle2 angle3 &allow-other-keys)
  (declare (ignore initargs))
  (cond ((and center radius axis R angle1 angle2 angle3)
	 (error "Ambiguous arguments to overloaded constructor."))
	((and center radius)
	 (assert (typep center 'gp:pnt))
	 (assert (typep radius 'double-float))
	 (setf (ff-pointer obj)
	       (_wrap_new_BRepPrimAPI_MakeSphere__SWIG_0 (ff-pointer center) radius))
	 (oc:finalize obj)
	 (values))
	((and axis R angle1 angle2 angle3)
	 (assert (typep axis 'gp:ax2))
	 (assert (typep R 'double-float))
	 (assert (typep angle1 'double-float))
	 (assert (typep angle2 'double-float))
	 (assert (typep angle3 'double-float))
	 (_wrap_new_BRepPrimAPI_MakeSphere__SWIG_1 (ff-pointer axis) R angle1 angle2 angle3)
	 (oc:finalize obj)
	 (values))
	(t (error "Insufficient arguments to constructor."))))
